#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSS = ROOT / "css"
OUT = CSS / "home-bundle.css"
SOURCES = [
    "styles.css",
    "experience-v4.css",
    "brand-theme.css",
    "focal-position.css",
    "adaptive-commerce-v4.css",
    "visual-desire-v4.css",
    "resilience-v4.css",
    "premium-release-v4.css",
    "smart-pairing-v4-1-4.css",
    "intelligent-bag-v4-1-5.css",
    "accessibility-fortress-v4-1-8.css",
]

def render():
    chunks = [
        "/* GENERATED FILE — do not edit directly. Source order is performance-critical. */",
        "/* Generated by tools/build-home-css.py */",
    ]
    for name in SOURCES:
        source = CSS / name
        if not source.exists():
            raise SystemExit(f"Missing CSS source: {source}")
        text = source.read_text(encoding="utf-8-sig").strip()
        chunks.append(f"\n/* === {name} === */\n{text}")
    return "\n".join(chunks) + "\n"

OUT.write_text(render(), encoding="utf-8", newline="\n")
print(f"home css bundle: {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes, {len(SOURCES)} sources)")
