#!/usr/bin/env python3
from pathlib import Path
import json,re,sys
ROOT=Path(__file__).resolve().parents[1]
html=(ROOT/'index.html').read_text(encoding='utf-8')
checkout=(ROOT/'js/checkout.js').read_text(encoding='utf-8')
main=(ROOT/'js/main.js').read_text(encoding='utf-8')
commerce=(ROOT/'data/commerce-config.js').read_text(encoding='utf-8')
brand=json.loads((ROOT/'data/brand/brand.json').read_text(encoding='utf-8'))
changelog=(ROOT/'CHANGELOG.md').read_text(encoding='utf-8')
checks=[]
def check(name,ok,detail=''): checks.append((name,bool(ok),detail))
check('Delivery and pickup choices','checkout-fulfillment-delivery' in html and 'checkout-fulfillment-pickup' in html)
check('Pix and cash choices','checkout-payment-pix' in html and 'checkout-payment-cash' in html)
check('Cash change field','checkout-change-for' in html and 'Troco para' in html)
check('ASAP and scheduling choices','checkout-time-asap' in html and 'checkout-time-scheduled' in html)
check('Schedule validation uses business hours','validateSchedule' in checkout and 'commerce.hours' in checkout)
check('Pickup removes address requirement','data-pickup-fields' in html and 'fulfillment === "delivery"' in checkout)
check('Delivery area preserved','Aguarde a validação do CEP antes de continuar.' in checkout and 'addressMode === "blocked"' in checkout)
check('Operational uncertainty disclosed','Taxa de entrega confirmada no WhatsApp' in checkout and 'Prazo de entrega confirmado no WhatsApp' in checkout)
check('Availability runtime','unavailableProductIds' in commerce and 'isAvailable' in main and 'Indisponível hoje' in main)
check('Stored bag reconciliation','bagReconciliation' in main and 'preço foi atualizado' in main and 'item indisponível foi removido' in main)
check('Fuzzy search and aliases','editDistanceAtMostOne' in main and 'aliases' in main)
check('Cross-tab bag sync','addEventListener("storage"' in main and 'Sua Sacola foi atualizada por outra aba' in main)
check('Analytics disabled by default',brand.get('commerce',{}).get('analytics',{}).get('enabled') is False)
check('Offline fallback',(ROOT/'offline.html').exists() and 'offline.html' in (ROOT/'service-worker.js').read_text(encoding='utf-8'))
check('404 fallback',(ROOT/'404.html').exists())
check('FAQ privacy terms','Perguntas rápidas sobre o pedido' in html and 'Privacidade e dados' in html and 'Condições do pedido' in html)
check('No automatic WhatsApp','nada é enviado automaticamente' in html.lower() and 'window.open' in main)
check('Commerce config payments',set(brand.get('commerce',{}).get('payment',{}).get('methods',[]))=={'pix','cash'})
check('Pickup enabled',brand.get('commerce',{}).get('fulfillment',{}).get('pickup') is True)
check('Scheduling enabled',brand.get('commerce',{}).get('scheduling',{}).get('enabled') is True)
for patch in range(10): check(f'Changelog 2.8.{patch}',f'## 2.8.{patch} ' in changelog)
passed=sum(ok for _,ok,_ in checks)
for name,ok,detail in checks: print(('PASS' if ok else 'FAIL')+f'  {name}'+(f' — {detail}' if detail else ''))
print(f'\n{passed}/{len(checks)} commerce-operations checks passed')
if passed!=len(checks): sys.exit(1)
