#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
CSS = ROOT / "css"
SOURCES = [
    "styles.css",
    "experience-v4.css",
    "brand-theme.css",
    "focal-position.css",
    "adaptive-commerce-v4.css",
    "visual-desire-v4.css",
    "resilience-v4.css",
    "premium-release-v4.css",
    "smart-pairing-v4-1-4.css",
    "intelligent-bag-v4-1-5.css",
    "accessibility-fortress-v4-1-8.css",
]

def expected_bundle():
    chunks = [
        "/* GENERATED FILE — do not edit directly. Source order is performance-critical. */",
        "/* Generated by tools/build-home-css.py */",
    ]
    for name in SOURCES:
        text = (CSS / name).read_text(encoding="utf-8-sig").strip()
        chunks.append(f"\n/* === {name} === */\n{text}")
    return "\n".join(chunks) + "\n"

checks=[]
def check(label, condition):
    checks.append((label, bool(condition)))
    print(("PASS  " if condition else "FAIL  ") + label)

index=(ROOT/'index.html').read_text(encoding='utf-8')
bundle=(CSS/'home-bundle.css')
sw=(ROOT/'service-worker.js').read_text(encoding='utf-8')
package=(ROOT/'package.json').read_text(encoding='utf-8')
check('home bundle exists', bundle.exists())
check('home bundle is deterministic', bundle.exists() and bundle.read_text(encoding='utf-8') == expected_bundle())
check('home loads fonts locally', 'css/fonts-local.css' in index)
check('home loads one application stylesheet bundle', 'css/home-bundle.css' in index)
check('individual home source stylesheets are not linked', all(f'href="css/{name}"' not in index and f'href="./css/{name}"' not in index for name in SOURCES))
check('build regenerates home bundle', 'tools/build-home-css.py' in package)
check('quality verifies home bundle architecture', 'tools/home-style-bundle-check.py' in package)
check('service worker caches home bundle', './css/home-bundle.css' in sw)
check('service worker caches local fonts css', './css/fonts-local.css' in sw)
check('home CSP no longer grants Google Fonts', 'fonts.googleapis.com' not in index and 'fonts.gstatic.com' not in index)
failed=[name for name,ok in checks if not ok]
print(f"{len(checks)-len(failed)}/{len(checks)} home-style-bundle checks passed")
if failed: sys.exit(1)
