#!/usr/bin/env python3
from pathlib import Path
import json, sys
ROOT=Path(__file__).resolve().parents[1]
passed=[]; errors=[]
def check(cond,label): (passed if cond else errors).append(label)
admin=(ROOT/'admin/index.html').read_text(encoding='utf-8')
admin_js=(ROOT/'js/admin.js').read_text(encoding='utf-8')
core=(ROOT/'js/admin-core.js').read_text(encoding='utf-8')
history=(ROOT/'js/admin-history.js').read_text(encoding='utf-8')
persistence=(ROOT/'js/admin-persistence.js').read_text(encoding='utf-8')
css=(ROOT/'css/admin.css').read_text(encoding='utf-8')
build=(ROOT/'tools/build-site.py').read_text(encoding='utf-8')
brand=json.loads((ROOT/'data/brand/brand.json').read_text(encoding='utf-8'))
pkg=json.loads((ROOT/'package.json').read_text(encoding='utf-8'))
ch=(ROOT/'CHANGELOG.md').read_text(encoding='utf-8')
check(brand.get('credits',{}).get('name')=='KJ Productions','KJ Productions credit configuration')
check(brand.get('credits',{}).get('enabled') is True,'creator credit enabled by default')
check('site-credit' in (ROOT/'index.html').read_text(encoding='utf-8'),'home creator credit')
check('CREDIT_NAME' in build and 'site-credit' in build,'generated page creator credit')
check('credit-enabled' in admin and 'credit-name' in admin,'admin credit controls')
check('admin-mode' in admin and 'dataset.adminMode' in admin_js,'simple/advanced mode')
check('admin-search-dialog' in admin and 'searchActions' in admin_js,'admin action search')
check('change-history' in admin and 'ADMIN_HISTORY' in admin_js,'session change history')
check('undo-button' in admin and 'history.undo()' in admin_js,'undo action')
check('admin-preview' in admin and 'updatePreview' in admin_js,'draft preview')
check('onboarding-dialog' in admin and 'ONBOARDING_KEY' in admin_js,'first-use onboarding')
check('ADMIN_PERSISTENCE' in persistence and 'createLocalDraftRepository' in persistence,'persistence adapter')
check('draftRepository' in admin_js,'admin uses persistence adapter')
check('automaticPublish: false' in persistence and 'backendRequiredForRemoteWrite: true' in persistence,'remote publishing boundary explicit')
check('admin-history.js' not in (ROOT/'service-worker.js').read_text(encoding='utf-8'),'admin history excluded from public cache')
check('admin-persistence.js' not in (ROOT/'service-worker.js').read_text(encoding='utf-8'),'admin persistence excluded from public cache')
check('admin-advanced' in css and 'data-admin-mode="simple"' in css,'simple mode CSS contract')
check('admin-dialog' in css and '@media(max-width:36rem)' in css,'adaptive dialogs')
check('forced-colors:active' in css,'forced colors preserved')
check('prefers-reduced-motion:reduce' in css,'reduced motion preserved')
check('innerHTML' not in admin_js and 'insertAdjacentHTML' not in admin_js,'admin workflow avoids unsafe HTML sinks')
check('ADMIN_HISTORY' in history and 'snapshots.length > 1' in history,'bounded undo history')
check('projectVersion: version' in core,'bundle version remains explicit')
check('operator-experience-check.py' in pkg.get('scripts',{}).get('quality',''),'operator gate in quality')
for patch in range(10): check(f'## 3.5.{patch} ' in ch,f'changelog 3.5.{patch}')
if errors:
    print('OPERATOR EXPERIENCE CHECK FAILED')
    for label in errors: print('FAIL ',label)
    sys.exit(1)
for label in passed: print('PASS ',label)
print(f'{len(passed)}/{len(passed)} operator-experience checks passed')
