#!/usr/bin/env python3
from pathlib import Path
import json,re,sys
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(p): return (ROOT/p).read_text(encoding='utf-8')
def check(name,cond): checks.append((name,bool(cond)))
pkg=json.loads(text('package.json'))
manifest=json.loads(text('data/release-manifest-v4.json'))
index=text('index.html'); admin=text('admin/index.html'); sw=text('service-worker.js'); build=text('tools/build-site.py')
check('version 3.4.0', pkg.get('version')=='3.4.0')
check('app meta 3.4.0', 'version: "3.4.0"' in text('js/app-meta.js'))
check('service worker 3.4.0', 'const VERSION = "3.4.0"' in sw)
check('root HTML 3.4.0', 'content="3.4.0"' in index or 'content="3.4.0" name="x-project-version"' in index)
check('admin HTML 3.4.0', 'content="3.4.0"' in admin and 'Admin Studio v3.4.0' in admin)
check('release manifest 3.4.0', manifest.get('version')=='3.4.0' and manifest.get('name')=='3.4.0 Stabilization Release')
status=manifest.get('status',{})
run=status.get('lastWindowsBrowserRun',{})
browser_status=status.get('browserMatrix')
browser_honest=(browser_status in {'PENDING_WINDOWS_EXECUTION','RETEST_REQUIRED_AFTER_3.4.0_FIX'} or (browser_status=='WINDOWS_CHROMIUM_PASS_403' and run.get('passed')==403 and run.get('failed')==0 and run.get('skipped')==17))
check('release manifest honest browser status', browser_honest)
check('release manifest honest NVDA status', status.get('nvda') in {'MANUAL_REQUIRED','MANUAL_PASS'})
check('release manifest honest TalkBack status', status.get('talkback') in {None,'MANUAL_PASS'})
check('unclaimed screen readers remain explicit', status.get('otherScreenReaders') in {None,'NOT_TESTED_NO_ACCESS'})
check('fortress sitewide generator', 'css/accessibility-fortress-v4-1-8.css' in build)
check('fortress in service worker shell', 'css/accessibility-fortress-v4-1-8.css' in sw)
check('signature release docs', (ROOT/'docs/RELEASE-3.4.0.md').exists() and (ROOT/'docs/SIGNATURE-COMMERCE-4.1.9.md').exists())
check('signature evidence ledger', (ROOT/'docs/releases/evidence/v4.1.9/summary.md').exists())
check('signature E2E exists', (ROOT/'tests/e2e/signature-commerce-v4-1-9.spec.js').exists())
check('signature behavior gate wired', 'signature-commerce-v4-1-9-behavior-check.js' in pkg.get('scripts',{}).get('quality',''))
check('signature release gate wired', 'release-v4-1-9-check.py' in pkg.get('scripts',{}).get('quality',''))
failed=[n for n,ok in checks if not ok]
for n,ok in checks: print(('PASS' if ok else 'FAIL').ljust(5),n)
print(f'{len(checks)-len(failed)}/{len(checks)} Signature Commerce checks passed')
if failed: sys.exit(1)
